"""worked? 3

Revision ID: 3449abbcc0aa
Revises: baf429983108
Create Date: 2024-03-17 00:37:18.045471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3449abbcc0aa'
down_revision = 'baf429983108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_users_id'), 'book_users', ['id'], unique=False)
    op.create_index(op.f('ix_book_users_username'), 'book_users', ['username'], unique=True)
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_department_title'), 'department', ['title'], unique=True)
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('year', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('copies_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    op.create_table('book_copy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['book_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_copy_id'), 'book_copy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_copy_id'), table_name='book_copy')
    op.drop_table('book_copy')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_department_title'), table_name='department')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_book_users_username'), table_name='book_users')
    op.drop_index(op.f('ix_book_users_id'), table_name='book_users')
    op.drop_table('book_users')
    # ### end Alembic commands ###
