"""update users

Revision ID: acea9fb205d6
Revises: 3449abbcc0aa
Create Date: 2024-03-17 09:33:53.775361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acea9fb205d6'
down_revision = '3449abbcc0aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_users_username', table_name='book_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_book_users_username', 'book_users', ['username'], unique=False)
    # ### end Alembic commands ###
