"""related names

Revision ID: b132fe31c91a
Revises: acea9fb205d6
Create Date: 2024-03-18 22:05:10.128191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b132fe31c91a'
down_revision = 'acea9fb205d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
